### ISSUE TITLE
Generated Javadoc does not automatically indent if previous line is not indented

### ISSUE THREAD

**Issue by syoon2** [Trelent/Trelent-VSCode-Extension#1]
## Environment
- VSCode version: 1.63.2 (stable)
- Trelent version: 1.5.0
- Other extensions installed: themes only

## Steps to repro:
```java
public class Fibonacci {

    public static int fibonacci(int n) throws IllegalArgumentException {
        if (n < 0) throw new IllegalArgumentException();
        if (n == 0) return 0;
        if (n == 1) return 1;
        return fibonacci(n - 2) + fibonacci(n - 1);
    }
}
```
1. Make `Fibonacci.java` as shown above (note line 2 is _not_ indented)
2. `Alt+D` `fibonacci()`
3. Observe generated Javadoc not being indented

Note: If line 2 is indented, generated javadoc is also indented.

**Comment by syoon2** [comment]
Also occurs in VSCode version 1.65.0 (latest stable)

**Comment by calum-bird** [comment]
Nice find! Patching in the next patch release (hopefully this weekend).

**Comment by Coolroo** [comment]
Should be fixed with new update :)
